spring:
  config:
    import: classpath:local/local.env[.properties]
  application:
    name: todo_api
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/todo_api_db
    username: admin
    password: ${TIM95BELL_TODO_API_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  # NOTE(TB): had to disable self signed ssl in dev build as other server does not trust it
  # ssl:
  #   key-store: classpath:local/certificate.p12
  #   key-store-type: PKCS12
  #   key-store-password: ${TIM95BELL_TODO_API_SSL_CERTIFICATE_PASSWORD}
  port: ${TIM95BELL_TODO_API_PORT}

key_set_uri: ${TIM95BELL_TODO_AS_URL}/oauth2/jwks
