spring:
  config:
    import: classpath:local/local.env[.properties]
  application:
    name: todo
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/todo_db
    username: admin
    password: ${TIM95BELL_TODO_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  ssl:
    key-alias: todo-https
    key-store: classpath:local/tim95bell.todo.jks
    key-store-type: JKS
    key-store-password: ${TIM95BELL_TODO_SSL_KEY_STORE_PASSWORD}
    key-password: ${TIM95BELL_TODO_SSL_KEY_PASSWORD}
