name: todo_api
services:
  db:
    image: mariadb:${TIM95BELL_TODO_API_MARIADB_VERSION}
    container_name: todo_api_db
    build: .
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${TIM95BELL_TODO_API_DB_ROOT_PASSWORD}
      MARIADB_PASSWORD: ${TIM95BELL_TODO_API_DB_PASSWORD}
      MARIADB_USER: admin
      MARIADB_DATABASE: todo_api_db
